<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.3" />
    <PackageReference Include="Slugify.Core" Version="5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelSwipe.Activities.Core\TravelSwipe.Activities.Core.csproj" />
  </ItemGroup>

</Project>
