<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="MassTransit" Version="8.5.8" />
		<PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
		<ProjectReference Include="..\Cities.Core\Cities.Core.csproj" />
		<ProjectReference Include="..\TravelSwipe.Core\TravelSwipe.Core.csproj" />
	</ItemGroup>

</Project>
