<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4" />
		<PackageReference Include="FluentAssertions" Version="8.9.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.14" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="Mongo2Go" Version="4.1.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Testcontainers.PostgreSql" Version="4.11.0" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.extensibility.core" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Activities.Application\Activities.Application.csproj" />
	  <ProjectReference Include="..\Activities.Core\Activities.Core.csproj" />
	  <ProjectReference Include="..\Activities.Infrastructure\Activities.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>