<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>994661bf-473a-48af-aca4-2737c39c646c</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.14" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.5.8" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\Cities.Application\Cities.Application.csproj" />
		<ProjectReference Include="..\Cities.Core\Cities.Core.csproj" />
		<ProjectReference Include="..\Cities.Infrastructure\Cities.Infrastructure.csproj" />
		<ProjectReference Include="..\TravelSwipe.Core\TravelSwipe.Core.csproj" />
	</ItemGroup>

</Project>
