<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>adab924e-181f-49db-a2e6-061541cd6f27</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.14" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.14" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.14" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TravelSwipe.Activities.Application\Activities.Application.csproj" />
		<ProjectReference Include="..\TravelSwipe.Activities.Infrastructure\Activities.Infrastructure.csproj" />
	</ItemGroup>

</Project>
