// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelSwipe.Infrastructure.data;

#nullable disable

namespace TravelSwipe.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301180233_RenameToSnakeCase")]
    partial class RenameToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelSwipe.Core.Features.Cities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Municipality")
                        .HasColumnType("text")
                        .HasColumnName("municipality");

                    b.PrimitiveCollection<List<string>>("Name")
                        .HasColumnType("text[]")
                        .HasColumnName("name");

                    b.Property<string>("NameClean")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_clean");

                    b.Property<string>("Postcode")
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.PrimitiveCollection<List<string>>("State")
                        .HasColumnType("text[]")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("TravelSwipe.Core.Features.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.PrimitiveCollection<List<string>>("Name")
                        .HasColumnType("text[]")
                        .HasColumnName("name");

                    b.Property<string>("NameClean")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_clean");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("TravelSwipe.Core.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FacebookId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("facebook_id");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("User", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
