// <auto-generated />
using System.Collections.Generic;
using Cities.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cities.Infrastructure.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20260314212316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cities.Core.Features.Cities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("AssociatedNames")
                        .HasColumnType("text[]")
                        .HasColumnName("associated_names");

                    b.PrimitiveCollection<List<string>>("AssociatedSlugs")
                        .HasColumnType("text[]")
                        .HasColumnName("associated_slugs");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Municipality")
                        .HasColumnType("text")
                        .HasColumnName("municipality");

                    b.Property<string>("Postcode")
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.PrimitiveCollection<List<string>>("State")
                        .HasColumnType("text[]")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_city_display_name");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("Cities.Core.Features.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("ix_country_display_name");

                    b.ToTable("Country", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
